// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(openclipboardFFI)
import openclipboardFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_openclipboard_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_openclipboard_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOpenclipboardFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ClipboardNodeProtocol: AnyObject, Sendable {
    
    func connectAndSendFile(addr: String, filePath: String) throws 
    
    func connectAndSendText(addr: String, text: String) throws 
    
    func peerId()  -> String
    
    func startListener(port: UInt16, handler: EventHandler) throws 
    
    func stop() 
    
}
open class ClipboardNode: ClipboardNodeProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_openclipboard_ffi_fn_clone_clipboardnode(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_openclipboard_ffi_fn_free_clipboardnode(pointer, $0) }
    }

    

    
open func connectAndSendFile(addr: String, filePath: String)throws   {try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_clipboardnode_connect_and_send_file(self.uniffiClonePointer(),
        FfiConverterString.lower(addr),
        FfiConverterString.lower(filePath),$0
    )
}
}
    
open func connectAndSendText(addr: String, text: String)throws   {try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_clipboardnode_connect_and_send_text(self.uniffiClonePointer(),
        FfiConverterString.lower(addr),
        FfiConverterString.lower(text),$0
    )
}
}
    
open func peerId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_clipboardnode_peer_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func startListener(port: UInt16, handler: EventHandler)throws   {try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_clipboardnode_start_listener(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),
        FfiConverterCallbackInterfaceEventHandler_lower(handler),$0
    )
}
}
    
open func stop()  {try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_clipboardnode_stop(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClipboardNode: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClipboardNode

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClipboardNode {
        return ClipboardNode(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClipboardNode) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClipboardNode {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClipboardNode, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardNode_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClipboardNode {
    return try FfiConverterTypeClipboardNode.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipboardNode_lower(_ value: ClipboardNode) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClipboardNode.lower(value)
}






public protocol IdentityProtocol: AnyObject, Sendable {
    
    func info()  -> IdentityInfo
    
    func peerId()  -> String
    
    func pubkeyB64()  -> String
    
    func save(path: String) throws 
    
}
open class Identity: IdentityProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_openclipboard_ffi_fn_clone_identity(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_openclipboard_ffi_fn_free_identity(pointer, $0) }
    }

    

    
open func info() -> IdentityInfo  {
    return try!  FfiConverterTypeIdentityInfo_lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_identity_info(self.uniffiClonePointer(),$0
    )
})
}
    
open func peerId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_identity_peer_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func pubkeyB64() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_identity_pubkey_b64(self.uniffiClonePointer(),$0
    )
})
}
    
open func save(path: String)throws   {try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_identity_save(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentity: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Identity

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Identity {
        return Identity(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Identity) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Identity {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Identity, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentity_lift(_ pointer: UnsafeMutableRawPointer) throws -> Identity {
    return try FfiConverterTypeIdentity.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentity_lower(_ value: Identity) -> UnsafeMutableRawPointer {
    return FfiConverterTypeIdentity.lower(value)
}






public protocol PairingPayloadProtocol: AnyObject, Sendable {
    
    func identityPk()  -> [UInt8]
    
    func lanPort()  -> UInt16
    
    func name()  -> String
    
    func nonce()  -> [UInt8]
    
    func peerId()  -> String
    
    func toQrString() throws  -> String
    
    func version()  -> UInt8
    
}
open class PairingPayload: PairingPayloadProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_openclipboard_ffi_fn_clone_pairingpayload(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_openclipboard_ffi_fn_free_pairingpayload(pointer, $0) }
    }

    

    
open func identityPk() -> [UInt8]  {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_pairingpayload_identity_pk(self.uniffiClonePointer(),$0
    )
})
}
    
open func lanPort() -> UInt16  {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_pairingpayload_lan_port(self.uniffiClonePointer(),$0
    )
})
}
    
open func name() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_pairingpayload_name(self.uniffiClonePointer(),$0
    )
})
}
    
open func nonce() -> [UInt8]  {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_pairingpayload_nonce(self.uniffiClonePointer(),$0
    )
})
}
    
open func peerId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_pairingpayload_peer_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func toQrString()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_pairingpayload_to_qr_string(self.uniffiClonePointer(),$0
    )
})
}
    
open func version() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_method_pairingpayload_version(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairingPayload: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PairingPayload

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PairingPayload {
        return PairingPayload(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PairingPayload) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairingPayload {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PairingPayload, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairingPayload_lift(_ pointer: UnsafeMutableRawPointer) throws -> PairingPayload {
    return try FfiConverterTypePairingPayload.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairingPayload_lower(_ value: PairingPayload) -> UnsafeMutableRawPointer {
    return FfiConverterTypePairingPayload.lower(value)
}






public protocol TrustStoreProtocol: AnyObject, Sendable {
    
    func add(peerId: String, identityPkB64: String, displayName: String) throws 
    
    func get(peerId: String) throws  -> TrustRecord?
    
    func list() throws  -> [TrustRecord]
    
    func remove(peerId: String) throws  -> Bool
    
}
open class TrustStore: TrustStoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_openclipboard_ffi_fn_clone_truststore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_openclipboard_ffi_fn_free_truststore(pointer, $0) }
    }

    

    
open func add(peerId: String, identityPkB64: String, displayName: String)throws   {try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_truststore_add(self.uniffiClonePointer(),
        FfiConverterString.lower(peerId),
        FfiConverterString.lower(identityPkB64),
        FfiConverterString.lower(displayName),$0
    )
}
}
    
open func get(peerId: String)throws  -> TrustRecord?  {
    return try  FfiConverterOptionTypeTrustRecord.lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_truststore_get(self.uniffiClonePointer(),
        FfiConverterString.lower(peerId),$0
    )
})
}
    
open func list()throws  -> [TrustRecord]  {
    return try  FfiConverterSequenceTypeTrustRecord.lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_truststore_list(self.uniffiClonePointer(),$0
    )
})
}
    
open func remove(peerId: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_method_truststore_remove(self.uniffiClonePointer(),
        FfiConverterString.lower(peerId),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrustStore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TrustStore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TrustStore {
        return TrustStore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TrustStore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrustStore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TrustStore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrustStore_lift(_ pointer: UnsafeMutableRawPointer) throws -> TrustStore {
    return try FfiConverterTypeTrustStore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrustStore_lower(_ value: TrustStore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTrustStore.lower(value)
}




public struct IdentityInfo {
    public var peerId: String
    public var pubkeyB64: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peerId: String, pubkeyB64: String) {
        self.peerId = peerId
        self.pubkeyB64 = pubkeyB64
    }
}

#if compiler(>=6)
extension IdentityInfo: Sendable {}
#endif


extension IdentityInfo: Equatable, Hashable {
    public static func ==(lhs: IdentityInfo, rhs: IdentityInfo) -> Bool {
        if lhs.peerId != rhs.peerId {
            return false
        }
        if lhs.pubkeyB64 != rhs.pubkeyB64 {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(peerId)
        hasher.combine(pubkeyB64)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentityInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IdentityInfo {
        return
            try IdentityInfo(
                peerId: FfiConverterString.read(from: &buf), 
                pubkeyB64: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: IdentityInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.peerId, into: &buf)
        FfiConverterString.write(value.pubkeyB64, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityInfo_lift(_ buf: RustBuffer) throws -> IdentityInfo {
    return try FfiConverterTypeIdentityInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityInfo_lower(_ value: IdentityInfo) -> RustBuffer {
    return FfiConverterTypeIdentityInfo.lower(value)
}


public struct TrustRecord {
    public var peerId: String
    public var identityPkB64: String
    public var displayName: String
    public var createdAtMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peerId: String, identityPkB64: String, displayName: String, createdAtMs: UInt64) {
        self.peerId = peerId
        self.identityPkB64 = identityPkB64
        self.displayName = displayName
        self.createdAtMs = createdAtMs
    }
}

#if compiler(>=6)
extension TrustRecord: Sendable {}
#endif


extension TrustRecord: Equatable, Hashable {
    public static func ==(lhs: TrustRecord, rhs: TrustRecord) -> Bool {
        if lhs.peerId != rhs.peerId {
            return false
        }
        if lhs.identityPkB64 != rhs.identityPkB64 {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.createdAtMs != rhs.createdAtMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(peerId)
        hasher.combine(identityPkB64)
        hasher.combine(displayName)
        hasher.combine(createdAtMs)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrustRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrustRecord {
        return
            try TrustRecord(
                peerId: FfiConverterString.read(from: &buf), 
                identityPkB64: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                createdAtMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TrustRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.peerId, into: &buf)
        FfiConverterString.write(value.identityPkB64, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterUInt64.write(value.createdAtMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrustRecord_lift(_ buf: RustBuffer) throws -> TrustRecord {
    return try FfiConverterTypeTrustRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrustRecord_lower(_ value: TrustRecord) -> RustBuffer {
    return FfiConverterTypeTrustRecord.lower(value)
}


public enum OpenClipboardError: Swift.Error {

    
    
    case Other(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOpenClipboardError: FfiConverterRustBuffer {
    typealias SwiftType = OpenClipboardError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OpenClipboardError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Other(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OpenClipboardError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Other(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpenClipboardError_lift(_ buf: RustBuffer) throws -> OpenClipboardError {
    return try FfiConverterTypeOpenClipboardError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpenClipboardError_lower(_ value: OpenClipboardError) -> RustBuffer {
    return FfiConverterTypeOpenClipboardError.lower(value)
}


extension OpenClipboardError: Equatable, Hashable {}




extension OpenClipboardError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}







public protocol EventHandler: AnyObject, Sendable {
    
    func onClipboardText(peerId: String, text: String, tsMs: UInt64) 
    
    func onFileReceived(peerId: String, name: String, dataPath: String) 
    
    func onPeerConnected(peerId: String) 
    
    func onPeerDisconnected(peerId: String) 
    
    func onError(message: String) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventHandler {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceEventHandler] = [UniffiVTableCallbackInterfaceEventHandler(
        onClipboardText: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            text: RustBuffer,
            tsMs: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onClipboardText(
                     peerId: try FfiConverterString.lift(peerId),
                     text: try FfiConverterString.lift(text),
                     tsMs: try FfiConverterUInt64.lift(tsMs)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onFileReceived: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            name: RustBuffer,
            dataPath: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onFileReceived(
                     peerId: try FfiConverterString.lift(peerId),
                     name: try FfiConverterString.lift(name),
                     dataPath: try FfiConverterString.lift(dataPath)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPeerConnected: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPeerConnected(
                     peerId: try FfiConverterString.lift(peerId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPeerDisconnected: { (
            uniffiHandle: UInt64,
            peerId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPeerDisconnected(
                     peerId: try FfiConverterString.lift(peerId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceEventHandler.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface EventHandler: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitEventHandler() {
    uniffi_openclipboard_ffi_fn_init_callback_vtable_eventhandler(UniffiCallbackInterfaceEventHandler.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceEventHandler {
    fileprivate static let handleMap = UniffiHandleMap<EventHandler>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceEventHandler : FfiConverter {
    typealias SwiftType = EventHandler
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventHandler_lift(_ handle: UInt64) throws -> EventHandler {
    return try FfiConverterCallbackInterfaceEventHandler.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventHandler_lower(_ v: EventHandler) -> UInt64 {
    return FfiConverterCallbackInterfaceEventHandler.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTrustRecord: FfiConverterRustBuffer {
    typealias SwiftType = TrustRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTrustRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTrustRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTrustRecord: FfiConverterRustBuffer {
    typealias SwiftType = [TrustRecord]

    public static func write(_ value: [TrustRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTrustRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TrustRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [TrustRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTrustRecord.read(from: &buf))
        }
        return seq
    }
}
public func clipboardNodeNew(identityPath: String, trustPath: String)throws  -> ClipboardNode  {
    return try  FfiConverterTypeClipboardNode_lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_func_clipboard_node_new(
        FfiConverterString.lower(identityPath),
        FfiConverterString.lower(trustPath),$0
    )
})
}
public func defaultIdentityPath() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_func_default_identity_path($0
    )
})
}
public func deriveConfirmationCode(nonce: [UInt8], peerAId: String, peerBId: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_func_derive_confirmation_code(
        FfiConverterSequenceUInt8.lower(nonce),
        FfiConverterString.lower(peerAId),
        FfiConverterString.lower(peerBId),$0
    )
})
}
public func identityGenerate() -> Identity  {
    return try!  FfiConverterTypeIdentity_lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_func_identity_generate($0
    )
})
}
public func identityLoad(path: String)throws  -> Identity  {
    return try  FfiConverterTypeIdentity_lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_func_identity_load(
        FfiConverterString.lower(path),$0
    )
})
}
public func pairingPayloadCreate(version: UInt8, peerId: String, name: String, identityPk: [UInt8], lanPort: UInt16, nonce: [UInt8]) -> PairingPayload  {
    return try!  FfiConverterTypePairingPayload_lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_func_pairing_payload_create(
        FfiConverterUInt8.lower(version),
        FfiConverterString.lower(peerId),
        FfiConverterString.lower(name),
        FfiConverterSequenceUInt8.lower(identityPk),
        FfiConverterUInt16.lower(lanPort),
        FfiConverterSequenceUInt8.lower(nonce),$0
    )
})
}
public func pairingPayloadFromQrString(s: String)throws  -> PairingPayload  {
    return try  FfiConverterTypePairingPayload_lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_func_pairing_payload_from_qr_string(
        FfiConverterString.lower(s),$0
    )
})
}
public func trustStoreDefaultPath() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openclipboard_ffi_fn_func_trust_store_default_path($0
    )
})
}
public func trustStoreOpen(path: String)throws  -> TrustStore  {
    return try  FfiConverterTypeTrustStore_lift(try rustCallWithError(FfiConverterTypeOpenClipboardError_lift) {
    uniffi_openclipboard_ffi_fn_func_trust_store_open(
        FfiConverterString.lower(path),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_openclipboard_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_clipboard_node_new() != 34405) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_default_identity_path() != 36700) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_derive_confirmation_code() != 57345) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_identity_generate() != 23125) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_identity_load() != 25055) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_pairing_payload_create() != 8324) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_pairing_payload_from_qr_string() != 47962) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_trust_store_default_path() != 22940) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_func_trust_store_open() != 31823) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_clipboardnode_connect_and_send_file() != 14460) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_clipboardnode_connect_and_send_text() != 48151) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_clipboardnode_peer_id() != 3503) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_clipboardnode_start_listener() != 7176) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_clipboardnode_stop() != 10276) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_identity_info() != 2247) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_identity_peer_id() != 44450) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_identity_pubkey_b64() != 60910) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_identity_save() != 46504) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_pairingpayload_identity_pk() != 27340) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_pairingpayload_lan_port() != 37867) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_pairingpayload_name() != 25511) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_pairingpayload_nonce() != 37717) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_pairingpayload_peer_id() != 16212) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_pairingpayload_to_qr_string() != 16160) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_pairingpayload_version() != 57585) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_truststore_add() != 40678) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_truststore_get() != 64463) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_truststore_list() != 17484) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_truststore_remove() != 28281) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_eventhandler_on_clipboard_text() != 36399) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_eventhandler_on_file_received() != 14273) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_eventhandler_on_peer_connected() != 9467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_eventhandler_on_peer_disconnected() != 30734) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openclipboard_ffi_checksum_method_eventhandler_on_error() != 400) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEventHandler()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOpenclipboardFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all