// swift-tools-version: 6.0

import Foundation
import PackageDescription

let env = ProcessInfo.processInfo.environment
let defaultLibDir = "../target/debug"
let ffiLibDir = env["OPENCLIPBOARD_FFI_LIB_DIR"] ?? defaultLibDir

let package = Package(
    name: "OpenClipboard",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .executable(name: "OpenClipboard", targets: ["OpenClipboard"])
    ],
    targets: [
        // C header target generated by UniFFI.
        .target(
            name: "openclipboardFFI",
            path: "openclipboardFFI",
            publicHeadersPath: "include"
        ),

        // Generated Swift bindings (depends on the C header).
        .target(
            name: "OpenClipboardBindings",
            dependencies: ["openclipboardFFI"],
            path: "OpenClipboardBindings",
            linkerSettings: [
                // Link to the Rust cdylib built by cargo.
                // CI sets OPENCLIPBOARD_FFI_LIB_DIR to the folder containing libopenclipboard_ffi.dylib
                .unsafeFlags(["-L\(ffiLibDir)", "-lopenclipboard_ffi"]),
                // For app bundles, allow @executable_path/../Frameworks.
                .unsafeFlags(["-Xlinker", "-rpath", "-Xlinker", "@executable_path/../Frameworks"]),
            ]
        ),

        .executableTarget(
            name: "OpenClipboard",
            dependencies: ["OpenClipboardBindings"],
            path: "OpenClipboard"
        ),

        .testTarget(
            name: "OpenClipboardTests",
            dependencies: ["OpenClipboardBindings"],
            path: "Tests/OpenClipboardTests"
        ),
    ]
)
